{
    'name' : 'Documents Administratifs',
    'version' : '1.1',
    'summary': 'Documents Administratifs',
    'sequence': 10,
    'description': "Documents Administratifs",

    'depends' : [
        'base',
        'hr',
        'web',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/document_administratif.xml',
        'views/autorisation_absence.xml',
        'views/autorisation_conge.xml',
        'views/cessation_service.xml',
        'views/certificat_travail.xml',
        'views/attestation_salariale.xml',
        'views/prime_rendement.xml',
        'views/prise_service.xml',
        'views/certificat_administratif.xml',
        'views/paiement_cessation.xml',
        'views/suspension_contrat.xml',
        'views/conge_maternite.xml',
        'views/conge_administratif.xml',
        'views/decision_affectation.xml',
        'views/decision_nomination.xml',
        'views/action_menu.xml',
        'report/template_document.xml',
        'report/document.xml',
        'report/template_absence.xml',
        'report/absence.xml',
        'report/template_conge.xml',
        'report/conge.xml',
        'report/template_cessation_service.xml',
        'report/cesse_service.xml',
        'report/template_certificat_travail.xml',
        'report/cer_travail.xml',
        'report/template_attestation_salariale.xml',
        'report/attest_salariale.xml',
        'report/template_prime_rendement.xml',
        'report/p_rendement.xml',
        'report/template_prise_service.xml',
        'report/p_service.xml',
        'report/template_certificat_administratif.xml',
        'report/c_administratif.xml',
        'report/template_conge_maternite.xml',
        'report/co_maternite.xml',
        'report/template_conge_administratif.xml',
        'report/co_administratif.xml',
        'report/template_cp.xml',
        'report/pem_css.xml',
        'report/template_aff_deci.xml',
        'report/aff_deci.xml',
        'report/template_nomination.xml',
        'report/nomination.xml',
    ],
    'installable': True,
    'application': True,
}