{
    "name": "Gestion de la paie",
    "version": "1.0",
    "author": "TELIA INFORMATIQUE",
    "depends":["base","hr_payroll","referentiel","Gestion_RH"],
    "data":[
        "security/paie_security.xml",
        "security/ir.model.access.csv",
        "views/etat_nominatif_paie.xml",
        "views/etat_synthese_paie.xml",
        "views/vue_paie.xml",
        "views/rappel_precompte.xml",
        "views/vue_report_bulletin.xml",
        "views/vue_report_etat.xml",
        "Report/report_etat_nominatif_paie.xml",
        "Report/report_etat_synthese_paie.xml",
        "Report/report_mode_paiement.xml",
        "Report/report_par_banque.xml",
        "Report/report_elt_salaire.xml",
        "Report/report_part_agent.xml",
        "Report/report_part_patronal.xml",
        "Report/report_part_global.xml",
        "Report/report_cessation_paiement.xml",
        "Report/report_prime.xml",
        "Report/report_massesalariale.xml",
        "data/paie.xml",
        "data/sequence.xml",],
    "category": "EPE",
    "Summary": "Gestion de la paie des EPE",
    "installable": True,
    "auto_install": False,

}
